### ISSUE TITLE
Cold start doesn't work

### ISSUE THREAD

**Issue by jmarca** [hoodiehq/hoodie-app-mapchat#20]
Hi,

Following the instructions in the README doesn't result in a working app.  Not sure what is going on.

I cloned the repo, ran npm install --production, then npm start.  There was a warning about admin account being disabled:

```
james@emma hoodie-app-mapchat[master]$ npm start

> hoodie-app-mapchat@1.0.2 start /home/james/repos/hoodie_stuff/hoodie-app-mapchat
> hoodie

WARN log 2017-02-14T17:34:31.769Z [ 'account' ] Admin account disabled: `options.adminPassword` not set
Your Hoodie app has started on: http://localhost:8080
Stop server with control + c
```

Navigating to localhost:8080 on my laptop shows a blank blue screen and a search bar:

![screenshot_20170214_093902](https://cloud.githubusercontent.com/assets/70304/22941198/71f54336-f299-11e6-8fd6-57617d601be2.png)

The firefox developer dialog shows no issues with missing network files, but the console does show the message:

```
Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead[Learn More]  jquery.min.js:1
Error: hoodie.account not yet accessible, wait for hoodie.ready to resolve  client.js:1069:15
Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.  jquery.min.js:3:31293
Error: hoodie.account not yet accessible, wait for hoodie.ready to resolve  client.js:1069:15
```

Clearly I need to somehow activate "hoodie.account" but not sure what to do.

node version v7.2.0
firefox 50.1.0
running couchdb 1.6.2, but it didn't seem like the hoodie app cared about that at all, and I couldn't see where/how to link that up.

**Comment by gr2m** [comment]
> Clearly I need to somehow activate "hoodie.account" but not sure what to do

I think I know what the problem is. We recently made the hoodie client API fully async, which now requires the API to be initialised before it can be used. 

Instead of calling `hoodie.account.isSignedIn()` and other APIs, you know have to do this:

```js
hoodie.ready.then(function () {
  if (hoodie.account.isSignedIn()) {
    // ...
  }
})
```

It will need a pull request similar to this one: https://github.com/hoodiehq/hoodie-app-tracker/pull/118

Would you like to give it a try? I’m happy to help you

**Comment by jmarca** [comment]
Sure I'm sure I can hack that out.  

Give me a day or two to get to it.

**Comment by gr2m** [comment]
awesome, thanks James!

**Comment by jmarca** [comment]
Okay, more than a day or two!  Getting to this today.

**Comment by gr2m** [comment]
Please don’t feel bad, no problem at all :)

**Comment by capellini** [comment]
@jmarca - we've just pushed an update that should resolve this issue.  Would you mind quickly confirming that you're not seeing this problem anymore?

**Comment by jmarca** [comment]
yep, those problems seem to be gone.  

What I did:
0. checked out master (git checkout master)
1. pulled from github:master (git pull)
2. npm install --production

See some warnings:
```
hoodie-app-mapchat[master]$ npm install --production
npm WARN deprecated nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/

> hoodie@28.2.1 postinstall /home/james/repos/hoodie_stuff/hoodie-app-mapchat/node_modules/hoodie
> node ./bin/setup.js

info setup Start your Hoodie app with "npm start"
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN hoodie-app-mapchat@1.0.2 No repository field.
npm WARN hoodie-app-mapchat@1.0.2 No license field.

added 169 packages, removed 193 packages and updated 630 packages in 34.072s
```

3. started the app:

```
 hoodie-app-mapchat[master]$ npm start

> hoodie-app-mapchat@1.0.2 start /home/james/repos/hoodie_stuff/hoodie-app-mapchat
> hoodie

Your Hoodie app has started on: http://localhost:8080
Stop server with control + c
```

4. Navigated to 127.0.0.1:8080 using firefox, I can see the map, can log in, etc.

Some other issues, (had an alert icon about not logged in until reloaded page; can't add markers; can't recenter map on my location (even though on start it picks Los Angeles fine)) but those are *other issues*.  I'm going to close this one.  Thanks.
